### ISSUE TITLE
tensorflow-gpu pip wheels for Windows platform

### ISSUE THREAD

**Issue by levicki** [NVIDIA/tensorflow#1]
For anyone who is trying to use TensorFlow on Windows with recent NVIDIA hardware and latest CUDA libraries installed, the only option seems to be compiling tensorflow-gpu manually. The reason is that TensorFlow is always [lagging behind CUDA](https://www.tensorflow.org/install/gpu#software_requirements) sometimes it is even more than one version behind.

There were numerous requests on TensorFlow issue tracker to provide `tensorflow-gpu` builds with the latest CUDA libraries but all of them were ultimately rejected.

While it is probably possible to have more than one CUDA toolkit version installed to work around this issue, it just needlessly complicates things for developers.

It would be nice if NVIDIA stepped up and provided pip wheels for Windows platform built against latest CUDA version for both TensorFlow 1.15 and 2.x.

**Comment by DEKHTIARJonathan** [comment]
We are currently evaluating if we could support windows tensorflow releases. I can't give you any estimate for now.

You can always look in WSL2 which should temporarily solve your issue on windows ;)

**Comment by levicki** [comment]
> You can always look in WSL2 which should temporarily solve your issue on windows ;)

If I am not mistaken, WSL2 GPU support would require being on the insider ring? Sadly, I don't have a spare PC for that and I am not in the habit of risking my everyday PC, personal data and code with alpha software builds.

**Comment by DEKHTIARJonathan** [comment]
> If I am not mistaken, WSL2 GPU support would require being on the insider ring ?

Doesn't look like: https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by levicki** [comment]
> Doesn't look like: https://docs.microsoft.com/en-us/windows/wsl/install-win10

That is just for the WSL2 itself, for CUDA support in WSL2 you need to be on a Windows Insider Dev Channel build 20150 or higher:

https://docs.microsoft.com/en-us/windows/win32/direct3d12/gpu-cuda-in-wsl

**Comment by carlfm01** [comment]
Hello @DEKHTIARJonathan, any news?

**Comment by rallandr** [comment]
I am also struggling with RTX30x0 series incompatibility with TF 1.15. I hope there will be a solution soon

**Comment by DEKHTIARJonathan** [comment]
@carlfm01 when there will be news, we will update. For now it is not on the road map any time soon.
The official solution will be to use WSL2 or Ubuntu ;) 

If it can help: https://docs.nvidia.com/cuda/wsl-user-guide/index.html

**Comment by levicki** [comment]
You keep saying how WSL2 is a solution, but it is really not a solution at all not to have a native pip wheel, not to mention how you conveniently ignore the fact that hardware acceleration under WSL2 works only in insider builds of Windows which means it is not even officially supported yet.

I understand that most CUDA stuff comes for Linux first, but I don't understand how a multi-billion dollar company size of NVIDIA cannot afford to produce official Tensorflow-GPU builds for relevant operating systems.

Unless Windows is not relevant.

**Comment by levicki** [comment]
Once again, WSL is not a solution:

![image](https://user-images.githubusercontent.com/16415478/100226820-8ca4c680-2f20-11eb-84f4-b72bfe2ca756.png)

You are basically asking Windows developers to run an unstable alpha version of the operating system and to risk losing data.

Also, your smug comment about using Ubuntu is really unprofessional.

**Comment by Fannhhyy** [comment]
> We are currently evaluating if we could support windows tensorflow releases. I can't give you any estimate for now.
> 
> You can always look in WSL2 which should temporarily solve your issue on windows ;)

```
2021-01-05 13:55:11.175995: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-01-05 13:55:11.776548: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-01-05 13:55:13.371893: W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Internal: ptxas exited with non-zero error code 65280, output: ptxas fatal   : Value 'sm_86' is not defined for option 'gpu-name'
```
I got rtx 3070 , and try it in wsl2 . The whl not support sm_86 , and ptxas not work with wsl2.

**Comment by johnny12150** [comment]
[This](https://github.com/fo40225/tensorflow-windows-wheel/tree/master/1.15.4+nv20.12/) pre-built wheel for Windows may help.

**Comment by levicki** [comment]
> [This](https://github.com/fo40225/tensorflow-windows-wheel/tree/master/1.15.4+nv20.12/) pre-built wheel for Windows may help.

I appreciate your help, but that is an unofficial and unsupported build by a 3rd party.

We need NVIDIA to step up and provide official tensorflow-gpu build for current CUDA version.

**Comment by cliffwoolley** [comment]
Thanks for your note, @levicki .  Formal support for Windows is not on our team's roadmap at this time, but we have raised this issue with our product management for future consideration.

**Comment by levicki** [comment]
@cliffwoolley Thanks I guess.
