### ISSUE TITLE
Pip install nvidia-pyindex keeps giving error

### ISSUE THREAD

**Issue by Muizzu001** [NVIDIA/tensorflow#12]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Nil
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.3.1
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 8
- GPU model and memory: Nvidia MX130

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Tried to execute pip install nvidia-pyindex but it does not work. Tried to upgrade pip, also does not work.

**Describe the expected behavior**

It gives this error:

`Processing c:\users\muizz\desktop\nvidia-pyindex-1.0.5.tar.gz
Building wheels for collected packages: nvidia-pyindex
  Building wheel for nvidia-pyindex (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\muizz\anaconda3\envs\fyp\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\muizz\\AppData\\Local\\Temp\\pip-req-build-_f5b70p_\\setup.py'"'"'; __file__='"'"'C:\\Users\\muizz\\AppData\\Local\\Temp\\pip-req-build-_f5b70p_\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\muizz\AppData\Local\Temp\pip-wheel-xoaw05hk'
       cwd: C:\Users\muizz\AppData\Local\Temp\pip-req-build-_f5b70p_\
  Complete output (25 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\nvidia_pyindex
  copying nvidia_pyindex\cmdline.py -> build\lib\nvidia_pyindex
  copying nvidia_pyindex\utils.py -> build\lib\nvidia_pyindex
  copying nvidia_pyindex\__init__.py -> build\lib\nvidia_pyindex
  running egg_info
  writing nvidia_pyindex.egg-info\PKG-INFO
  writing dependency_links to nvidia_pyindex.egg-info\dependency_links.txt
  writing entry points to nvidia_pyindex.egg-info\entry_points.txt
  writing top-level names to nvidia_pyindex.egg-info\top_level.txt
  reading manifest file 'nvidia_pyindex.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'nvidia_pyindex.egg-info\SOURCES.txt'
  installing to build\bdist.win-amd64\wheel
  running install
  '"nvidia_pyindex uninstall"' is not recognized as an internal or external command,
  operable program or batch file.
  error: [WinError 2] The system cannot find the file specified
  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  COMMAND: InstallCommand
  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  ----------------------------------------
  ERROR: Failed building wheel for nvidia-pyindex
  Running setup.py clean for nvidia-pyindex
Failed to build nvidia-pyindex
Installing collected packages: nvidia-pyindex
    Running setup.py install for nvidia-pyindex ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\muizz\anaconda3\envs\fyp\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\muizz\\AppData\\Local\\Temp\\pip-req-build-_f5b70p_\\setup.py'"'"'; __file__='"'"'C:\\Users\\muizz\\AppData\\Local\\Temp\\pip-req-build-_f5b70p_\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\muizz\AppData\Local\Temp\pip-record-7qi_408u\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\muizz\AppData\Roaming\Python\Python37\Include\nvidia-pyindex'
         cwd: C:\Users\muizz\AppData\Local\Temp\pip-req-build-_f5b70p_\
    Complete output (7 lines):
    running install
    '"nvidia_pyindex uninstall"' is not recognized as an internal or external command,
    operable program or batch file.
    error: [WinError 2] The system cannot find the file specified
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    COMMAND: InstallCommand
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\muizz\anaconda3\envs\fyp\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\muizz\\AppData\\Local\\Temp\\pip-req-build-_f5b70p_\\setup.py'"'"'; __file__='"'"'C:\\Users\\muizz\\AppData\\Local\\Temp\\pip-req-build-_f5b70p_\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\muizz\AppData\Local\Temp\pip-record-7qi_408u\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\muizz\AppData\Roaming\Python\Python37\Include\nvidia-pyindex' Check the logs for full command output.`

**Code to reproduce the issue**
Pip install nvidia-pyindex

**Other info / logs**
Nil

**Comment by nluehr** [comment]
Sorry. NVIDIA-PyIndex and NVIDIA/TensorFlow do not support Windows.

**Comment by Muizzu001** [comment]
I see. Thank you for the response!
