### ISSUE TITLE
Which tensorflow model version should be used for object detection

### ISSUE THREAD

**Issue by ButterMeWaffle** [NVIDIA/tensorflow#17]
I have been working on running this code to train my object detection model but I am not sure on which tensorflow model release I should use (https://github.com/tensorflow/models/releases). I have been trying to use v 1.13 but I am having issues with it using both GPUs even though it is detecting both of my 3080s

**Comment by DEKHTIARJonathan** [comment]
As far as I can see, there is not version of this repository compatible with Tensorflow 1.15.X
I highly suggest you to look into TensorFlow 2.0: **https://ngc.nvidia.com/catalog/containers/nvidia:tensorflow**
