### ISSUE TITLE
How to install with specific release?

### ISSUE THREAD

**Issue by johnny12150** [NVIDIA/tensorflow#20]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version: 3.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: 

**Describe the problem**
The latest version requires `Linux Ubuntu 20.04`.
How do I install the [previous versions](https://docs.nvidia.com/deeplearning/frameworks/tensorflow-wheel-release-notes/tf-wheel-rel.html#unique_615558829)?

**Provide the exact sequence of commands / steps that you executed before running into the problem**
`Could not find a version that satisfies the requirement nvidia-tensorflow[horovod]==1.15.4+nv20.11 (from versions: 0.0.1.dev4, 1.15.4+nv20.12, 1.15.5+nv21.2, 1.15.5+nv21.3)`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by DEKHTIARJonathan** [comment]
With Python 3.8 only: 1.15.4+nv20.12, 1.15.5+nv21.2, 1.15.5+nv21.3 are available.
Previous versions are only available with python 3.6
