### ISSUE TITLE
[tensorboard] Unable to get local issuer certificate _ssl.c:1091 /pypi/nvidia-tensorboard

### ISSUE THREAD

**Issue by elgalu** [NVIDIA/tensorflow#31]
### Issue
We have a corporate pypi (kind of man in the middle) index which makes nvidia-pyindex fail with:

```
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)'))': /pypi/nvidia-tensorboard/
```

### Request
Would it be possible that you open source nvidia-tensorboard so we can install it via git? or please provide nvidia py index url so we can pass it via `pip install --index-url=https://pypi.some-nvidia-url nvidia-tensorboard`

### System information
- Ubuntu 20.04
- Python 3.7.0 / 3.8.5 (same issue)

**Comment by elgalu** [comment]
I think I found the correct index url so won't need the magic from `nvidia-pyindex` that has conflicts with our enterprise setup.

```sh
pip uninstall -y tensorboard
pip install --index-url "https://developer.download.nvidia.com/compute/redist" nvidia-tensorboard
pip install --index-url "https://developer.download.nvidia.com/compute/redist" nvidia-tensorboard-plugin-dlprof
#=> installed tensorboard==1.15.0, nvidia-tensorboard==1.15.0+nv21.4, nvidia-tensorboard-plugin-dlprof==1.2.0
```

**Comment by DEKHTIARJonathan** [comment]
I would recommend you to use the alias 
https://pypi.ngc.nvidia.com

Technically does the exact same, though if we decide to change the endpoint using the alias will allow to migrate transparently.

Please close your issue if good 👌

**Comment by elgalu** [comment]
awesome!
