### ISSUE TITLE
The libc version required by the wheel is too new (2.29) for many systems; consider being more conservative

### ISSUE THREAD

**Issue by guicho271828** [NVIDIA/tensorflow#32]
I could get around the issue with LD_PRELOAD because apparently the only requirement is libm, but this is not ideal.

```
export LD_PRELOAD=$HOME/.local/glibc-2.29/lib/libm.so.6
```

**Comment by bertsky** [comment]
Would it help to use [manylinux](https://github.com/pypa/manylinux) for the wheels?

(The only imports from GLIBC seem to be exp, exp2, log and log2 – I doubt these actually were updated recently.)

**Comment by samlobel** [comment]
This is a problem for me too, just hoping to bump the issue.

**Comment by dithwick** [comment]
Same here. A lot of HPC clusters are running Redhat/CentOS/Rocky 8 where the glibc is 2.28. manylinux2014  looks like it would work for us in this case.

**Comment by thorstenwagner** [comment]
We are facing the same problem on several HPC systems

**Comment by rhamnett** [comment]
This is still a major issue. EL9 (glibc 2.29) is not even out which means that 2.28 is the currently wide standard. Can we get this built back with glibc 2.28?

**Comment by nluehr** [comment]
Starting with the 22.01 release, the wheel is built in a manylinux environment which includes libc 2.12. This should significantly improve portability.

**Comment by thorstenwagner** [comment]
Perfect! Do you already know when the release will happen? :-)

28.01.2022 23:59:56 Nathan Luehr ***@***.***>:

**Comment by nluehr** [comment]
It was released earlier today.
```
pip install nvidia-tensorflow==1.15.5+nv22.1
```

**Comment by thorstenwagner** [comment]
Great! Problem is solved for me :-)

Thanks for the package!

29.01.2022 01:01:16 Nathan Luehr ***@***.***>:

**Comment by guicho271828** [comment]
Thanks!
