### ISSUE TITLE
Can't install in Colab and Kaggle

### ISSUE THREAD

**Issue by qo4on** [NVIDIA/tensorflow#34]
I tried this in Colab and Kaggle (Python 3.7 both) and got an error.
```
!pip install nvidia-pyindex
!pip install nvidia-tensorflow==1.15.4
```
ERROR: Could not find a version that satisfies the requirement nvidia-tensorflow==1.15.4 (from versions: 0.0.1.dev4, 0.0.1.dev5)
ERROR: No matching distribution found for nvidia-tensorflow==1.15.4

Is it possible to use `nvidia-tensorflow` in Kaggle?

**Comment by DEKHTIARJonathan** [comment]
We don't support Python 3.7. Only Python 3.8
