### ISSUE TITLE
compile from source can not git clone cudnn_frontend_archive

### ISSUE THREAD

**Issue by aixi** [NVIDIA/tensorflow#37]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Centos 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 15.5/r21.06
- Python version: 3.7
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 0.25.3
- GCC/Compiler version (if compiling from source): g++ 7.3
- CUDA/cuDNN version: cuda 11.1 update 1, cuDNN 8.1.33
- GPU model and memory: tesla T4

**Describe the problem**

git clone https://oauth2:***/cudnn/cudnn_frontend.git failed

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by cliffwoolley** [comment]
This was an issue in 21.06 corrected in later releases.  You'll need to have a local copy of the cudnn_frontend repo checked out at the correct path.  @nluehr we should probably fix the top level .gitmodules accordingly.

**Comment by aixi** [comment]
> This was an issue in 21.06 corrected in later releases. You'll need to have a local copy of the cudnn_frontend repo checked out at the correct path. @nluehr we should probably fix the top level .gitmodules accordingly.

thank for your reply, where can I found a correct cudnn_frontend, can you gave me a http link or something ?

**Comment by cliffwoolley** [comment]
@aixi The original reference was to an internal commit that's not on GitHub at the exact same hash, but it was a point in time a few commits prior to https://github.com/NVIDIA/cudnn-frontend/tree/v0.4 that is nearly identical to https://github.com/NVIDIA/cudnn-frontend/commit/8fea413ec242bec36e69e5d07516b76a580fdabb -- so that one is your best bet, but v0.4 (or later) is likely also safe.

**Comment by nouiz** [comment]
Here is a diff that fix the issue:
```
diff --git a/tensorflow/workspace2.bzl b/tensorflow/workspace2.bzl
index 08a69af50cd..693e1018cb7 100644
--- a/tensorflow/workspace2.bzl
+++ b/tensorflow/workspace2.bzl
@@ -158,10 +158,10 @@ def _tf_repositories():
     new_git_repository(
         name = "cudnn_frontend_archive",
         build_file = "//third_party:cudnn_frontend.BUILD",
-        patches = ["//third_party:cudnn_frontend_header_fix.patch"],
-        patch_args = ['-p1'],
-        commit = "e9ad21cc61f8427bbaed98045b7e4f24bad57619",
-        remote = "https://oauth2:J64G8MymaUmqNKG_N3rR@gitlab-master.nvidia.com/cudnn/cudnn_frontend.git"
+        #patches = ["//third_party:cudnn_frontend_header_fix.patch"],
+       #        patch_args = ['-p1'],
+        commit = "73210a9",
+        remote = "https://github.com/NVIDIA/cudnn-frontend.git",
     )
```
