### ISSUE TITLE
FP16 implementation of Einsum OpKernel

### ISSUE THREAD

**Issue by donglinz** [NVIDIA/tensorflow#40]
**System information**
- TensorFlow version (you are using): 1.15.5
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
After enabling TF_ENABLE_AUTO_MIXED_PRECISION, Einsum operator throw below exception, saying Einsum operator do not have corresponding FP16 implementation
```
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'Einsum' OpKernel for 'GPU' devices compatible with node node StatefulPartitionedCall/model/bert_encoder/transformer/layer_0/self_attention/key/einsum/Einsum (defined at /usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/ops.py:1748) 
         (OpKernel was found, but attributes didn't match) Requested Attributes: N=2, T=DT_HALF, equation="abc,cde->abde", _device="/job:localhost/replica:0/task:0/device:GPU:0"
        .  Registered:  device='GPU'; T in [DT_COMPLEX128]
  device='GPU'; T in [DT_COMPLEX64]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_FLOAT]

         [[StatefulPartitionedCall/model/bert_encoder/transformer/layer_0/self_attention/key/einsum/Einsum]]
```

**Will this change the current api? How?**

No

**Who will benefit with this feature?**

Einsum operation is widely adopted in existing networks, FP16 implementation will benefit researcher/engineers who are intensively using  mix-precision training/inference.

**Any Other info.**
Einsum operation: https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/einsum

**Comment by donglinz** [comment]
I did a little bit more experiment, looks Einsum FP16 op is in tf2 but not in nvidia tf1.15

**Comment by DEKHTIARJonathan** [comment]
Please close this issue
