### ISSUE TITLE
releases or tags please?

### ISSUE THREAD

**Issue by rarensu** [NVIDIA/tensorflow#43]
Howdy, 

I am compiling nvidia-tensorflow from source for benchmarking purposes (yes, I know binaries are available) and I am worried because this repository doesn't seem to have very many releases or tags. You currently keep all of your critical version information in the names of the branches. Thus, I can't guarantee that whatever I do now will work for someone else in the future, if y'all decide to append or remove your branches. Would you be willing to mark your critical version information with releases or tags so my colleagues can feel safe that they will still be there in the future? Maybe for example, since branch `r1.15.4-nv20.12` hasn't changed in awhile, put a tag like `v1.15.4-nv20.12-stable` on the end of it. 

Have a good day, 
Richard

**Comment by nluehr** [comment]
We have started tagging monthly releases in addition to posting code branches. Thanks for the feedback.
