### ISSUE TITLE
Nvidia-tensorflow[horovod] installation fails due to an HTML issue on the website.

### ISSUE THREAD

**Issue by Subash-Chandra** [NVIDIA/tensorflow#50]
**System information**
- Windows Desktop with Intel i7 CPU and RTX 2080 Super
- Python3.8.12 installed through pip on Anaconda.  through command conda create --name nvidiatf python=3.8
- Trying to install Tensorflow using this command provided in the tutorial section of this repository
- $ pip install --user nvidia-tensorflow[horovod]
- CUDA/cuDNN version: Cuda Compilation Tools release 10.0 V10.0.130
- GPU model and memory: 8GB RTX 2080 Super

When I try to install Nvidia Tensorflow through pip through anaconda using the command provided on this tutorial, it does not work. Other repositories are able to be pip installed, and everything is upgraded. It is a new instance with only python and nvidia-pyindex installed which was the previous step in the tutorial.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I create an instance with Python 3.8 and I update pip and then install pyindex and then run this command to install tensorflow[horovod].

This is the error that actually shows up when I run this install command.
![image](https://user-images.githubusercontent.com/29782637/152785609-f40351ac-dd2f-4e61-82c5-b22c39f1eab0.png)

**Comment by nluehr** [comment]
At present Windows is not supported by the NVIDIA pip packages. See the [relnotes](https://docs.nvidia.com/deeplearning/frameworks/tensorflow-wheel-release-notes/tf-wheel-rel.html) for details.
