### ISSUE TITLE
Where can I find function clear_allocator_type() and set_allocator_type() defination 

### ISSUE THREAD

**Issue by zhuhejia** [NVIDIA/tensorflow#51]
When I was reading:

https://github.com/NVIDIA/tensorflow/blob/e43091019d5c3be599a3151fc565e67052d8aa2a/triton/tensorflow_backend_tf.cc#L940
https://github.com/NVIDIA/tensorflow/blob/e43091019d5c3be599a3151fc565e67052d8aa2a/triton/tensorflow_backend_tf.cc#L931

I wondered where function clear_allocator_type() in line 940 and set_allocator_type() in line 931 are defined. I did not find any file in tensorflow related with this function.

**Comment by nluehr** [comment]
These are generated from the GPUOptions protobuf definition [here](https://github.com/NVIDIA/tensorflow/blob/e8ccad6016357e5ba5c0d4cf1829532f967e840f/tensorflow/core/protobuf/config.proto#L50).
