### ISSUE TITLE
Is this fork dead?

### ISSUE THREAD

**Issue by plopresti** [NVIDIA/tensorflow#7]
We want to use TF1.15 on our brand-new A100 systems. We need to compile from source because we use the C/C++ bindings, and these not usually available from prebuilt releases (e.g. the container images on nvcr.io).

But the mainline r1.15 code does not support CUDA 11 and CUDNN 8. And the owners appear to have no interest in fixing this.

So, is NVIDIA releasing its source code for TF1.x after 2020-06?

Thank you!

**Comment by nluehr** [comment]
Updated branches have been made available. The latest is [r1.15.4+nv20.10](https://github.com/NVIDIA/tensorflow/tree/r1.15.4+nv20.10)

**Comment by plopresti** [comment]
Thanks!
