### ISSUE TITLE
developer.download.nvidia.cn not available

### ISSUE THREAD

**Issue by oasis-0927** [NVIDIA/tensorflow#81]
After install nvidia-pyindex through pip, when I try to install some other packages, pip will try to seek this package in pypi.ngc.nvidia.com, which will be redirected to https://developer.download.nvidia.com/compute/redist.  If the machine is located in China, it seems that developer.download.nvidia.com site will be automatically redirected to developer.download.nvidia.cn. Unfortunately, the .cn hostname is not supported by most public DNS in China. 
As a result, the installation of nvidia-pyindex will stop me from install any other package through pip. Is there any way to bypass it without modify the local hosts file?

**Comment by yanhuiyi** [comment]
@JuntingGuo Can you please write down each steps to reproduce the issue?
And what's your client IP and your ISP.

**Comment by oasis-0927** [comment]
> @JuntingGuo Can you please write down each steps to reproduce the issue? And what's your client IP and your ISP.

Hi,
Thank you for your reply. 
After trying out on hosts from different brands, I found this issue not certainly reproducible. My guess is that this issue is caused by the wrong configuration of the CDN or DNS that used by certain cloud host. 
I'll reopen this issue if I find out the precise problem.
