### ISSUE TITLE
pip >= 20.3 required, not 19.0

### ISSUE THREAD

**Issue by nanoflooder** [NVIDIA/tensorflow#82]
## URL(s) with the issue:

https://github.com/NVIDIA/tensorflow#readme

## Description of issue (what needs changing):

**Readme says in requirements: "pip 19.0 or later"**

## Suggested fix

**pip 20.3 or later**

## Explanation

- `nvidia-tensorflow[horovod]` depends on `tensorrt`
- `tensorrt` is distributed using `Manylinux_2_17`
- `Manylinux_x_y` requires `pip >= 20.3` (source: https://github.com/pypa/manylinux#readme)

The reason why this is important is because Ubuntu 20.04 only has `pip 20.0` in its repositories. When trying to install `nvidia-tensorflow[horovod]` with an outdated pip, it stumbles on `tensorrt` with the following error:

> Could not find a version that satisfies the requirement tensorrt~=8.5

When trying to install `tensorrt` manually by downloading the .whl, it says:

> tensorrt-8.5.3.1-cp38-none-manylinux_2_17_x86_64.whl is not a supported wheel on this platform

Being a linux/python newbie, I spent quite some time figuring out what went wrong, so perhaps this will save somebody's time in the future

**Comment by nluehr** [comment]
Thanks for calling this to our attention.
The README has been updated.
