### ISSUE TITLE
Simple patch on tensorflow v1.15.* to support cuda11.0 only

### ISSUE THREAD

**Issue by evanrang** [NVIDIA/tensorflow#9]
Hi, I suppose to run tensorflow v1.15.0 on NVIDIA A100, however, origin tensorflow v1.15.0 only support cuda10.0, but A100 need cuda11.0. Fortunately I found NVIDIA/tensorflow support both tensorflow v1.15.2 and cuda11.0, thank you all.

However, NVIDIA/tensorflow branch r1.15.2+nv20.06 contains not only cuda11.0 support, but also a lot of NVIDIA's tensorflow features which have no relationship with cuda11.0. Could NVIDIA support a simple patch on v1.15.* to support cuda11.0 only, which without NVIDIA's tensorflow features? For me, v1.15.0 base on is better, thank you all.

**Comment by rangjiaheng** [comment]
> Hi, I suppose to run tensorflow v1.15.0 on NVIDIA A100, however, origin tensorflow v1.15.0 only support cuda10.0, but A100 need cuda11.0. Fortunately I found NVIDIA/tensorflow support both tensorflow v1.15.2 and cuda11.0, thank you all.
> 
> However, NVIDIA/tensorflow branch r1.15.2+nv20.06 contains not only cuda11.0 support, but also a lot of NVIDIA's tensorflow features which have no relationship with cuda11.0. Could NVIDIA support a simple patch on v1.15.* to support cuda11.0, and without NVIDIA's tensorflow features? For me, v1.15.0 base on is better, thank you all.

**Comment by DEKHTIARJonathan** [comment]
> For me, v1.15.0 base on is better, thank you all.

Could you detail this statement ? Thanks a lot.

**Comment by evanrang** [comment]
@DEKHTIARJonathan Thanks for reply. I noticed the earliest branch of NVIDIA/tensorflow was r1.15.2+nv20.06, I wonder could tensorflow v1.15.0 support cuda11.0 with a simple patch, since I use v1.15.0 a lot with lots of self-maintained patches, it's difficult for me to upgrade.
So, could NVIDIA support a simple patch on v1.15.0 to pure support cuda11.0? If not, how about a simple patch on v1.15.2 to pure support cuda11.0?
Thanks a lot.

**Comment by DEKHTIARJonathan** [comment]
I'm sorry to hear that but probably not. There is no way "to just issue a simple patch" (it would requires extensive testing, etc.). 
I believe Google Enterprise or GCP may offer a TF1 release for CUDA11, you may want to check with that.

I'm sorry about that.

**Comment by evanrang** [comment]
Thanks a lot.
